/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EADMOB_AUTODEFS_H
#define S3EADMOB_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ADMOB_NAME "s3eAdmob"
#define S3E_EXT_ADMOB_HASH 0xe5cd0a33

#endif /* !S3EADMOB_AUTODEFS_H */
