/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"

#include "s3eAdmob.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*s3eAdmobRegister_t)(s3eAdmobCallback cbid, s3eCallback fn, void* userData);
typedef  s3eResult(*s3eAdmobUnRegister_t)(s3eAdmobCallback cbid, s3eCallback fn);
typedef  s3eResult(*s3eAdmobStart_t)(const char* pub_id, int ad_type, int orientation, int x, int y);
typedef  s3eResult(*s3eAdmobResize_t)(int ad_type);
typedef  s3eResult(*s3eAdmobShow_t)();
typedef  s3eResult(*s3eAdmobRefresh_t)();
typedef  s3eResult(*s3eAdmobHide_t)();
typedef  s3eResult(*s3eAdmobMove_t)(int orientation, int x, int y);
typedef  s3eResult(*s3eAdmobShowInterstitial_t)(const char* med_id);
typedef  s3eResult(*s3eAdmobShowSplash_t)(const char* med_id);

/**
 * struct that gets filled in by s3eAdmobRegister
 */
typedef struct s3eAdmobFuncs
{
    s3eAdmobRegister_t m_s3eAdmobRegister;
    s3eAdmobUnRegister_t m_s3eAdmobUnRegister;
    s3eAdmobStart_t m_s3eAdmobStart;
    s3eAdmobResize_t m_s3eAdmobResize;
    s3eAdmobShow_t m_s3eAdmobShow;
    s3eAdmobRefresh_t m_s3eAdmobRefresh;
    s3eAdmobHide_t m_s3eAdmobHide;
    s3eAdmobMove_t m_s3eAdmobMove;
    s3eAdmobShowInterstitial_t m_s3eAdmobShowInterstitial;
    s3eAdmobShowSplash_t m_s3eAdmobShowSplash;
} s3eAdmobFuncs;

static s3eAdmobFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xe5cd0a33, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE, "error loading extension: s3eAdmob");
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xe5cd0a33, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eAdmobAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult s3eAdmobRegister(s3eAdmobCallback cbid, s3eCallback fn, void* userData)
{
    IwTrace(ADMOB_VERBOSE, ("calling s3eAdmob[0] func: s3eAdmobRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdmobRegister(cbid, fn, userData);
}

s3eResult s3eAdmobUnRegister(s3eAdmobCallback cbid, s3eCallback fn)
{
    IwTrace(ADMOB_VERBOSE, ("calling s3eAdmob[1] func: s3eAdmobUnRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdmobUnRegister(cbid, fn);
}

s3eResult s3eAdmobStart(const char* pub_id, int ad_type, int orientation, int x, int y)
{
    IwTrace(ADMOB_VERBOSE, ("calling s3eAdmob[2] func: s3eAdmobStart"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdmobStart(pub_id, ad_type, orientation, x, y);
}

s3eResult s3eAdmobResize(int ad_type)
{
    IwTrace(ADMOB_VERBOSE, ("calling s3eAdmob[3] func: s3eAdmobResize"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdmobResize(ad_type);
}

s3eResult s3eAdmobShow()
{
    IwTrace(ADMOB_VERBOSE, ("calling s3eAdmob[4] func: s3eAdmobShow"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdmobShow();
}

s3eResult s3eAdmobRefresh()
{
    IwTrace(ADMOB_VERBOSE, ("calling s3eAdmob[5] func: s3eAdmobRefresh"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdmobRefresh();
}

s3eResult s3eAdmobHide()
{
    IwTrace(ADMOB_VERBOSE, ("calling s3eAdmob[6] func: s3eAdmobHide"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdmobHide();
}

s3eResult s3eAdmobMove(int orientation, int x, int y)
{
    IwTrace(ADMOB_VERBOSE, ("calling s3eAdmob[7] func: s3eAdmobMove"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdmobMove(orientation, x, y);
}

s3eResult s3eAdmobShowInterstitial(const char* med_id)
{
    IwTrace(ADMOB_VERBOSE, ("calling s3eAdmob[8] func: s3eAdmobShowInterstitial"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdmobShowInterstitial(med_id);
}

s3eResult s3eAdmobShowSplash(const char* med_id)
{
    IwTrace(ADMOB_VERBOSE, ("calling s3eAdmob[9] func: s3eAdmobShowSplash"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

    return g_Ext.m_s3eAdmobShowSplash(med_id);
}
